[package]
name = "pqcat"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
rand = "0.9.1"
num-bigint = "0.4.6"
clap = { version = "4.5.21", features = ["derive"] }
criterion = "0.6.0"
itertools = "0.14.0"
sysinfo = "0.35.1"
csv = "1.3.1"
regex = "1.5"
memory-stats = "1.1.0"
